export const questions = [
  {
    id: 1,
    text: "What is your ideal bedtime and wake-up time?",
    options: ["Early to bed, early to rise", "Night owl", "Flexible"],
  },
  {
    id: 2,
    text: "How would you describe your cleanliness level?",
    options: ["Very tidy", "Moderately clean", "Messy"],
  },
  {
    id: 3,
    text: "What’s your preferred environment for noise levels?",
    options: ["Quiet and peaceful", "Moderate noise", "Lively and social"],
  },
  {
    id: 4,
    text: "Do you smoke, and how do you feel about living with a smoker?",
    options: [
      "I smoke",
      "I don’t mind if my roommate smokes",
      "I prefer a smoke-free home",
    ],
  },
  {
    id: 5,
    text: "How often do you expect to have guests over?",
    options: ["Rarely", "Occasionally", "Frequently"],
  },
  {
    id: 6,
    text: "How do you feel about sharing household items like kitchen utensils and groceries?",
    options: ["Happy to share", "Prefer keeping things separate", "Flexible"],
  },
  {
    id: 7,
    text: "What are your work or study habits like?",
    options: ["I work from home", "I have a 9-5 job", "My schedule varies"],
  },
  {
    id: 8,
    text: "How would you describe your socializing habits at home?",
    options: [
      "Introverted, need alone time",
      "Balanced, enjoy occasional hangouts",
      "Extroverted, love socializing",
    ],
  },
  {
    id: 9,
    text: "What is your preferred approach to handling conflicts?",
    options: [
      "Direct and open communication",
      "Take time to cool off first",
      "Avoid conflict",
    ],
  },
  {
    id: 10,
    text: "Do you have any dietary restrictions or preferences that a roommate should know about?",
    options: [
      "None",
      "Vegetarian or vegan",
      "Other (e.g., food allergies or specific diets",
    ],
  },
];


export const mates = [
    {
      name: "Alice Johnson",
      age: 29,
      gender: "Female",
      occupation: "Software Engineer",
      hobbies: ["Coding", "Hiking", "Reading"],
      livingEnvironment: "Quiet and peaceful",
      socialHabits: "Introverted, need alone time",
      bio: "Alice loves coding, hiking, and exploring new technologies.",
      image: "https://via.placeholder.com/150/FFB6C1/000000?text=Alice", // Replace with actual image URLs
    },
    {
      name: "Bob Smith",
      age: 34,
      gender: "Male",
      occupation: "Graphic Designer",
      hobbies: ["Digital Art", "Traveling", "Cooking"],
      livingEnvironment: "Moderate noise",
      socialHabits: "Balanced, enjoy occasional hangouts",
      bio: "Bob is passionate about creating stunning visuals and digital art.",
      image: "https://via.placeholder.com/150/87CEEB/000000?text=Bob",
    },
    {
      name: "Charlie Brown",
      age: 26,
      gender: "Non-Binary",
      occupation: "Content Writer",
      hobbies: ["Blogging", "Photography", "Fitness"],
      livingEnvironment: "Lively and social",
      socialHabits: "Extroverted, love socializing",
      bio: "Charlie enjoys storytelling and blogging about personal growth.",
      image: "https://via.placeholder.com/150/FFD700/000000?text=Charlie",
    },
    {
      name: "Alice Johnson",
      age: 29,
      gender: "Female",
      occupation: "Software Engineer",
      hobbies: ["Coding", "Hiking", "Reading"],
      livingEnvironment: "Quiet and peaceful",
      socialHabits: "Introverted, need alone time",
      bio: "Alice loves coding, hiking, and exploring new technologies.",
      image: "https://via.placeholder.com/150/FFB6C1/000000?text=Alice", // Replace with actual image URLs
    },
    {
      name: "Bob Smith",
      age: 34,
      gender: "Male",
      occupation: "Graphic Designer",
      hobbies: ["Digital Art", "Traveling", "Cooking"],
      livingEnvironment: "Moderate noise",
      socialHabits: "Balanced, enjoy occasional hangouts",
      bio: "Bob is passionate about creating stunning visuals and digital art.",
      image: "https://via.placeholder.com/150/87CEEB/000000?text=Bob",
    },
    {
      name: "Charlie Brown",
      age: 26,
      gender: "Non-Binary",
      occupation: "Content Writer",
      hobbies: ["Blogging", "Photography", "Fitness"],
      livingEnvironment: "Lively and social",
      socialHabits: "Extroverted, love socializing",
      bio: "Charlie enjoys storytelling and blogging about personal growth.",
      image: "https://via.placeholder.com/150/FFD700/000000?text=Charlie",
    },
    {
      name: "Alice Johnson",
      age: 29,
      gender: "Female",
      occupation: "Software Engineer",
      hobbies: ["Coding", "Hiking", "Reading"],
      livingEnvironment: "Quiet and peaceful",
      socialHabits: "Introverted, need alone time",
      bio: "Alice loves coding, hiking, and exploring new technologies.",
      image: "https://via.placeholder.com/150/FFB6C1/000000?text=Alice", // Replace with actual image URLs
    },
    {
      name: "Bob Smith",
      age: 34,
      gender: "Male",
      occupation: "Graphic Designer",
      hobbies: ["Digital Art", "Traveling", "Cooking"],
      livingEnvironment: "Moderate noise",
      socialHabits: "Balanced, enjoy occasional hangouts",
      bio: "Bob is passionate about creating stunning visuals and digital art.",
      image: "https://via.placeholder.com/150/87CEEB/000000?text=Bob",
    },
    {
      name: "Charlie Brown",
      age: 26,
      gender: "Non-Binary",
      occupation: "Content Writer",
      hobbies: ["Blogging", "Photography", "Fitness"],
      livingEnvironment: "Lively and social",
      socialHabits: "Extroverted, love socializing",
      bio: "Charlie enjoys storytelling and blogging about personal growth.",
      image: "https://via.placeholder.com/150/FFD700/000000?text=Charlie",
    },
    {
      name: "Alice Johnson",
      age: 29,
      gender: "Female",
      occupation: "Software Engineer",
      hobbies: ["Coding", "Hiking", "Reading"],
      livingEnvironment: "Quiet and peaceful",
      socialHabits: "Introverted, need alone time",
      bio: "Alice loves coding, hiking, and exploring new technologies.",
      image: "https://via.placeholder.com/150/FFB6C1/000000?text=Alice", // Replace with actual image URLs
    },
    {
      name: "Bob Smith",
      age: 34,
      gender: "Male",
      occupation: "Graphic Designer",
      hobbies: ["Digital Art", "Traveling", "Cooking"],
      livingEnvironment: "Moderate noise",
      socialHabits: "Balanced, enjoy occasional hangouts",
      bio: "Bob is passionate about creating stunning visuals and digital art.",
      image: "https://via.placeholder.com/150/87CEEB/000000?text=Bob",
    },
    {
      name: "Charlie Brown",
      age: 26,
      gender: "Non-Binary",
      occupation: "Content Writer",
      hobbies: ["Blogging", "Photography", "Fitness"],
      livingEnvironment: "Lively and social",
      socialHabits: "Extroverted, love socializing",
      bio: "Charlie enjoys storytelling and blogging about personal growth.",
      image: "https://via.placeholder.com/150/FFD700/000000?text=Charlie",
    },
  ];
  
