export const questions = [
  {
    id: 1,
    text: "What is your ideal daily routine?",
    options: [
      "Early riser, structured schedule",
      "Flexible, go with the flow",
      "Night owl, active in the evenings",
    ],
  },
  {
    id: 2,
    text: "How do you prefer to handle household chores?",
    options: [
      "Shared responsibilities",
      "Each person handles their own",
      "Hire a cleaning service",
    ],
  },
  {
    id: 3,
    text: "What is your preferred level of social interaction at home?",
    options: [
      "Minimal, I value my privacy",
      "Occasional hangouts",
      "Frequent gatherings and socializing",
    ],
  },
  {
    id: 4,
    text: "How do you feel about pets in the home?",
    options: [
      "I have pets and love them",
      "I’m okay with pets",
      "I prefer a pet-free home",
    ],
  },
  {
    id: 5,
    text: "What is your approach to managing shared expenses?",
    options: [
      "Split everything equally",
      "Pay for what you use",
      "Flexible, depends on the situation",
    ],
  },
  {
    id: 6,
    text: "What kind of environment do you prefer for studying or working?",
    options: [
      "Quiet and focused",
      "Background noise is fine",
      "Lively and collaborative",
    ],
  },
  {
    id: 7,
    text: "How do you handle conflicts or disagreements?",
    options: [
      "Direct and open communication",
      "Take time to cool off before discussing",
      "Avoid confrontation altogether",
    ],
  },
  {
    id: 8,
    text: "What is your ideal temperature setting at home?",
    options: [
      "Cool and breezy",
      "Moderate and comfortable",
      "Warm and cozy",
    ],
  },
  {
    id: 9,
    text: "How do you feel about sharing personal items like kitchenware or appliances?",
    options: [
      "Happy to share",
      "Prefer to keep things separate",
      "Flexible, depends on the item",
    ],
  },
  {
    id: 10,
    text: "What is your preferred way to spend weekends?",
    options: [
      "Relaxing at home",
      "Exploring and going out",
      "Hosting friends or family",
    ],
  },
];

export const mates = [
    {
      name: "Alice Johnson",
      age: 29,
      gender: "Female",
      occupation: "Software Engineer",
      hobbies: ["Coding", "Hiking", "Reading"],
      livingEnvironment: "Quiet and peaceful",
      socialHabits: "Introverted, need alone time",
      bio: "Alice loves coding, hiking, and exploring new technologies.",
      image: "https://via.placeholder.com/150/FFB6C1/000000?text=Alice", // Replace with actual image URLs
    },
    {
      name: "Bob Smith",
      age: 34,
      gender: "Male",
      occupation: "Graphic Designer",
      hobbies: ["Digital Art", "Traveling", "Cooking"],
      livingEnvironment: "Moderate noise",
      socialHabits: "Balanced, enjoy occasional hangouts",
      bio: "Bob is passionate about creating stunning visuals and digital art.",
      image: "https://via.placeholder.com/150/87CEEB/000000?text=Bob",
    },
    {
      name: "Charlie Brown",
      age: 26,
      gender: "Non-Binary",
      occupation: "Content Writer",
      hobbies: ["Blogging", "Photography", "Fitness"],
      livingEnvironment: "Lively and social",
      socialHabits: "Extroverted, love socializing",
      bio: "Charlie enjoys storytelling and blogging about personal growth.",
      image: "https://via.placeholder.com/150/FFD700/000000?text=Charlie",
    },
    {
      name: "Alice Johnson",
      age: 29,
      gender: "Female",
      occupation: "Software Engineer",
      hobbies: ["Coding", "Hiking", "Reading"],
      livingEnvironment: "Quiet and peaceful",
      socialHabits: "Introverted, need alone time",
      bio: "Alice loves coding, hiking, and exploring new technologies.",
      image: "https://via.placeholder.com/150/FFB6C1/000000?text=Alice", // Replace with actual image URLs
    },
    {
      name: "Bob Smith",
      age: 34,
      gender: "Male",
      occupation: "Graphic Designer",
      hobbies: ["Digital Art", "Traveling", "Cooking"],
      livingEnvironment: "Moderate noise",
      socialHabits: "Balanced, enjoy occasional hangouts",
      bio: "Bob is passionate about creating stunning visuals and digital art.",
      image: "https://via.placeholder.com/150/87CEEB/000000?text=Bob",
    },
    {
      name: "Charlie Brown",
      age: 26,
      gender: "Non-Binary",
      occupation: "Content Writer",
      hobbies: ["Blogging", "Photography", "Fitness"],
      livingEnvironment: "Lively and social",
      socialHabits: "Extroverted, love socializing",
      bio: "Charlie enjoys storytelling and blogging about personal growth.",
      image: "https://via.placeholder.com/150/FFD700/000000?text=Charlie",
    },
    {
      name: "Alice Johnson",
      age: 29,
      gender: "Female",
      occupation: "Software Engineer",
      hobbies: ["Coding", "Hiking", "Reading"],
      livingEnvironment: "Quiet and peaceful",
      socialHabits: "Introverted, need alone time",
      bio: "Alice loves coding, hiking, and exploring new technologies.",
      image: "https://via.placeholder.com/150/FFB6C1/000000?text=Alice", // Replace with actual image URLs
    },
    {
      name: "Bob Smith",
      age: 34,
      gender: "Male",
      occupation: "Graphic Designer",
      hobbies: ["Digital Art", "Traveling", "Cooking"],
      livingEnvironment: "Moderate noise",
      socialHabits: "Balanced, enjoy occasional hangouts",
      bio: "Bob is passionate about creating stunning visuals and digital art.",
      image: "https://via.placeholder.com/150/87CEEB/000000?text=Bob",
    },
    {
      name: "Charlie Brown",
      age: 26,
      gender: "Non-Binary",
      occupation: "Content Writer",
      hobbies: ["Blogging", "Photography", "Fitness"],
      livingEnvironment: "Lively and social",
      socialHabits: "Extroverted, love socializing",
      bio: "Charlie enjoys storytelling and blogging about personal growth.",
      image: "https://via.placeholder.com/150/FFD700/000000?text=Charlie",
    },
    {
      name: "Alice Johnson",
      age: 29,
      gender: "Female",
      occupation: "Software Engineer",
      hobbies: ["Coding", "Hiking", "Reading"],
      livingEnvironment: "Quiet and peaceful",
      socialHabits: "Introverted, need alone time",
      bio: "Alice loves coding, hiking, and exploring new technologies.",
      image: "https://via.placeholder.com/150/FFB6C1/000000?text=Alice", // Replace with actual image URLs
    },
    {
      name: "Bob Smith",
      age: 34,
      gender: "Male",
      occupation: "Graphic Designer",
      hobbies: ["Digital Art", "Traveling", "Cooking"],
      livingEnvironment: "Moderate noise",
      socialHabits: "Balanced, enjoy occasional hangouts",
      bio: "Bob is passionate about creating stunning visuals and digital art.",
      image: "https://via.placeholder.com/150/87CEEB/000000?text=Bob",
    },
    {
      name: "Charlie Brown",
      age: 26,
      gender: "Non-Binary",
      occupation: "Content Writer",
      hobbies: ["Blogging", "Photography", "Fitness"],
      livingEnvironment: "Lively and social",
      socialHabits: "Extroverted, love socializing",
      bio: "Charlie enjoys storytelling and blogging about personal growth.",
      image: "https://via.placeholder.com/150/FFD700/000000?text=Charlie",
    },
  ];

